### ISSUE TITLE
The average precision and the average recall have the same result values

### ISSUE THREAD

**Issue by jaku-soft** [PacktPublishing/Advanced-Deep-Learning-with-Keras#11]
https://github.com/PacktPublishing/Advanced-Deep-Learning-with-Keras/blob/7bfce716e89cee447726209a28469405413b19ed/chapter11-detection/ssd-11.6.1.py#L298

It seems that the calculation for fn (false negatives) is incomplete. 
With "fn = abs(len(gt_class_ids) - tp)" every fp (false positive) is also a fn (false negative).
Maybe it should be: "fn = abs(len(gt_class_ids) - tp - fp)"

**Comment by roatienza** [comment]
Thanks for pointing this out. Fixed.
