### ISSUE TITLE
possibly unnecessary multiplication at the mask_offset function?

### ISSUE THREAD

**Issue by enexs** [PacktPublishing/Advanced-Deep-Learning-with-Keras#12]
At the chapter11-detection/loss.py mask_offset function, multiplying offset with the mask (line 85) seems unnecessary to me, because the rows of the offset which are not assigned to an object are already zero. This is not a bug obviously, but maybe unnecessary, am I right?
Thank you

**Comment by roatienza** [comment]
Right. This is done for computational convenience and efficiency so we don't need to perform if-else logic.
