### ISSUE TITLE
possible error at calculating the number of boxes

### ISSUE THREAD

**Issue by enexs** [PacktPublishing/Advanced-Deep-Learning-with-Keras#13]
At chapter11-detection/data_generator.py , in get_n_boxes(self) function, at line 85, 
self.n_boxes += np.prod(shape) // self.n_anchors

to calculate the number of boxes, it should be divided by 4 (xmin, xmax, ymin, ymax) but not the "self.n_anchors". In default, n_anchors = aspect_ration(3) + 1 = 4 works, but if we change the aspect ratio, it will give an error.

thank you

**Comment by roatienza** [comment]
In  [`build_ssd()`](https://github.com/PacktPublishing/Advanced-Deep-Learning-with-Keras/blob/9873124634d18430764f97504f7aaf33dc813b2b/chapter11-detection/model.py#L97), each feature map has `shape = (height, width, n_anchors * 4)`. So, we divide it by `n_anchors` to get the number of bbox.

**Comment by enexs** [comment]
Thank you so much for this great github and the book!
