### ISSUE TITLE
Invalid Argument Error

### ISSUE THREAD

**Issue by mrshinest** [PacktPublishing/Advanced-Deep-Learning-with-Keras#14]
Hello, 
When I tried to run the dcgan, cgan or wagan mode. I have a same error. 
InvalidArgumentError:  You must feed a value for placeholder tensor 'discriminator_input_5' with dtype float and shape [?,28,28,1]
[[node discriminator_input_6 (defined at C:/Users/xx/xx/xx.py:181) ]] [Op:__inference_keras_scratch_graph_40533]
Function call stack:
keras_scratch_graph
(the tensor name changes every time).

**Comment by roatienza** [comment]
Hi, Pls check your TF2 install. I also noticed that you are running on Windows. The code and results were verified on Ubuntu Linux (18LTS) only. The code was tested again and worked fine on TF2.4.1. Sample result below.

![25000](https://user-images.githubusercontent.com/8848769/107476619-2c353500-6bb1-11eb-8545-d7e754187fa8.png)

**Comment by mrshinest** [comment]
I think this is a bug when using TF2 under Windows. Other model such as stack Gan works for me. I'll try to run this code under Linux. Thank you!
