### ISSUE TITLE
Error for dcgan-mnist-4.2.1.py 

### ISSUE THREAD

**Issue by ThinhNgVhust** [PacktPublishing/Advanced-Deep-Learning-with-Keras#15]
Thank you for your greate tutor. but when i run dcgan-mnist-4.2.1.py . It shows error:**tensorflow.python.framework.errors_impl.InvalidArgumentError: You must feed a value for placeholder tensor 'discriminator_input' with dtype float and shape [?,28,28,1]
	 [[{{node discriminator_input}}]]**

I just copy your code and run it and therefore it raise the error

**Comment by ThinhNgVhust** [comment]
Oh sorry acctually its a problem of tensorflow version. instead of using tf gpu 1.15.0. I change it into 2.0.0 and problem solved!

**Comment by roatienza** [comment]
Thanks for the correction...
