### ISSUE TITLE
 Error occurred when finalizing GeneratorDataset iterator | Trying to run image segmentation on custom dataset

### ISSUE THREAD

**Issue by MLHafizur** [PacktPublishing/Advanced-Deep-Learning-with-Keras#16]
Hello, I am trying to train the segmentation model on my custom dataset, which has two classes 1: Copper  and 2:Belmouth. 
I used generate_gt_segmentation.py codes to convert JSON to .npy file. 
While running the training process on google colab tf version 2.4.1 getting following error: 

```
tensorflow.python.framework.errors_impl.ResourceExhaustedError:  OOM when allocating tensor with shape[4,16,720,1280] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node fcn/ResNet56v2/conv2d_18/Conv2D (defined at fcn-12.3.1.py:154) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.
 [Op:__inference_train_function_16535]

Function call stack:
train_function

2021-04-05 18:46:10.106657: W tensorflow/core/kernels/data/generator_dataset_op.cc:107] Error occurred when finalizing GeneratorDataset iterator: Failed precondition: Python interpreter state is not initialized. The process may be terminated.
	 [[{{node PyFunc}}]]
```

I also noticed that data_generator.py code give the # of class = 4, which is wrong also number of classes supposed to be 3. How may I solve the issue?

**Comment by MLHafizur** [comment]
@roatienza

**Comment by roatienza** [comment]
Hi, For the OOM problem, pls adjust the batch size. The default is 4 for big memory GPUs like V100. For smaller GPUs like 1060Ti, pls use 1. 
For the number of classes, the data generator reads the npy file and automatically computes the number of unique classes based on the GT mask.
https://github.com/PacktPublishing/Advanced-Deep-Learning-with-Keras/blob/5d97af8ef5d8b32bda38bdaeb9137fb4f49674a1/chapter12-segmentation/data_generator.py#L51

Therefore, if you want to make n_classes=3 (inc bg), you have to prepare dataset with key=image_file_name and value=tensor_mask where the dim of tensor_mask is image_dim x 3. The tensor_mask defines the segmentation mask of each object in the image.

**Comment by MLHafizur** [comment]
Hi @roatienza Thank you for your help. For the number of classes, I am bit confused. Can you please tell me in where of the code, I have to change?

**Comment by roatienza** [comment]
Hi, The short answer is - unfortunately, it is not straightforward. You must change the image variable:

https://github.com/PacktPublishing/Advanced-Deep-Learning-with-Keras/blob/5d97af8ef5d8b32bda38bdaeb9137fb4f49674a1/chapter12-segmentation/utils/generate_gt_segmentation.py#L51

to something like:
`image = np.ones((w, h, n_classes), dtype="uint8")`

In your case,  `(w,h)` is your image dim and `n_classes = 3`, or 2 classes + 1 bg class.  

Assuming you have the polygon annotation using via tool, the mask will be set on the `bg` variable:

https://github.com/PacktPublishing/Advanced-Deep-Learning-with-Keras/blob/5d97af8ef5d8b32bda38bdaeb9137fb4f49674a1/chapter12-segmentation/utils/generate_gt_segmentation.py#L67

Rowel

**Comment by MLHafizur** [comment]
Hi @roatienza I am getting following error when trying to train Mask-RCNN model with customs images.I tried with different version of tensorflow, keras and open cv, but no luck yet. All it seems that all x values are under 1280 and y values are under 720. My image sizes are 1280 * 720. How may I solve this issue?

AssertionError: Assertion failed.
warning: source train not part of our classes, delegating to parent.
ERROR:root:Error processing image {'id': 'WIN_20210309_14_32_19_Pro.jpg', 'source': 'train', 'path': '/content/gdrive/MyDrive/vgg_promark/Image_Segmentation/train/train/WIN_20210309_14_32_19_Pro.jpg', 'width': 1280, 'height': 720, 'polygons': [{'name': 'polygon', 'all_points_x': [428, 357, 349, 347, 359, 339, 349, 340, 338, 346, 356, 349, 359, 360, 359, 354, 361, 372, 396, 415, 427, 429, 422, 410, 417, 423, 429], 'all_points_y': [190, 189, 189, 202, 220, 232, 255, 262, 280, 289, 291, 305, 320, 335, 357, 374, 385, 394, 398, 398, 381, 360, 325, 294, 276, 228, 214]}, {'name': 'polygon', 'all_points_x': [499, 442, 423, 419, 420, 439, 431, 423, 420, 416, 434, 426, 415, 419, 430, 457, 482, 506, 511, 527, 528, 519], 'all_points_y': [145, 139, 139, 155, 172, 184, 216, 254, 288, 303, 348, 397, 412, 423, 430, 422, 411, 404, 318, 249, 182, 151]}, {'name': 'polygon', 'all_points_x': [504, 463, 446, 445, 438, 445, 458, 475, 484, 490, 493, 498, 499, 496, 486, 483, 499], 'all_points_y': [504, 497, 501, 553, 609, 667, 665, 675, 680, 680, 669, 637, 616, 590, 547, 528, 524]}, {'name': 'polygon', 'all_points_x': [255, 233, 217, 204, 187, 154, 143, 140, 141, 155, 163, 159, 153, 154, 172, 261, 261, 256, 247, 253], 'all_points_y': [552, 552, 542, 536, 538, 541, 545, 568, 582, 592, 594, 607, 619, 632, 631, 642, 622, 602, 587, 568]}], 'r_object_name': ['Copper', 'Belmouth', 'Belmouth', 'Copper']}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mrcnn/model.py", line 1704, in data_generator
    use_mini_mask=config.USE_MINI_MASK)
  File "/usr/local/lib/python3.7/dist-packages/mrcnn/model.py", line 1261, in load_image_gt
    hooks=imgaug.HooksImages(activator=hook))
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/meta.py", line 470, in augment_image
    return self.augment_images([image], hooks=hooks)[0]
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/meta.py", line 603, in augment_images
    hooks=hooks
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/meta.py", line 2816, in _augment_images
    hooks=hooks
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/meta.py", line 603, in augment_images
    hooks=hooks
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/geometric.py", line 620, in _augment_images
    shear_samples, cval_samples, mode_samples, order_samples)
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/geometric.py", line 689, in _augment_images_by_samples
    return_matrix=return_matrices,
  File "/usr/local/lib/python3.7/dist-packages/imgaug/augmenters/geometric.py", line 956, in _warp_cv2
    borderValue=cval
cv2.error: OpenCV(3.4.2) /io/opencv/modules/imgproc/src/imgwarp.cpp:2610: error: (-215:Assertion failed) src.cols > 0 && src.rows > 0 in function 'warpAffine'

Process Process-1:
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
<ipython-input-25-616aafa67c99> in <module>()
----> 1 history = train(model, dataset_path, 5)

3 frames
/usr/local/lib/python3.7/dist-packages/keras/engine/training.py in fit_generator(self, generator, steps_per_epoch, epochs, verbose, callbacks, validation_data, validation_steps, class_weight, max_queue_size, workers, use_multiprocessing, shuffle, initial_epoch)
   2009                 batch_index = 0
   2010                 while steps_done < steps_per_epoch:
-> 2011                     generator_output = next(output_generator)
   2012 
   2013                     if not hasattr(generator_output, '__len__'):

StopIteration:

**Comment by roatienza** [comment]
It appears that the input to your MaskRCNN model is None. Pls check your input data just before it is passed to the model.

This issue is no longer about the book content and example code so I am closing it. Thank you.
