### ISSUE TITLE
Warning for dcgan-mnist-4.2.1.py

### ISSUE THREAD

**Issue by ea42gh** [PacktPublishing/Advanced-Deep-Learning-with-Keras#2]
```
UserWarning: Discrepancy between trainable weights and collected trainable weights, did you set `model.trainable` without calling `model.compile` after ?
```
I have yet to figure out whether this is a serious issue.
Is there a clean way to get rid of this warning?

**Comment by roatienza** [comment]
There is nothing to worry about this warning. The warning is misleading. You can actually double check that discriminator weights are frozen during adversarial training and unfrozen during discriminator training.

More info here: https://github.com/keras-team/keras/issues/8585#issuecomment-384873566
